### ISSUE TITLE
Spelling mistake in about section

### ISSUE THREAD

**Issue by Stitti** [NicolasPrats/DvBrowser#29]
In the about section of this repository instead of 'developers' you wrote 'developpers'

**Comment by ginow** [comment]
Yes this issue is at two places:

- ![image](https://github.com/NicolasPrats/DvBrowser/assets/15030674/8ce08502-dc6b-430b-ac4e-e73a5ba244a9)

- ![image](https://github.com/NicolasPrats/DvBrowser/assets/15030674/036b0c91-7bff-41dc-89c8-7e2ef0fd3875)

**Comment by NicolasPrats** [comment]
Both are fixed! Thank you!
