### ISSUE TITLE
Provide an easy way to initiate a Web API call to debug Custom API / Actions

### ISSUE THREAD

**Issue by devkeydet** [NicolasPrats/DvBrowser#4]
It would be a nice enhancement to provide a UI mechanism in the browser to make calls to the web API and debug the plugins behind those calls.  Most common use case for me would be Custom API.  
https://learn.microsoft.com/en-us/power-apps/developer/data-platform/custom-api

Even if it's rudimentary like postman, would be nice.

**Comment by NicolasPrats** [comment]
Hi @devkeydet ,

I have started to implement Custom Api support in the branch [CustomApi](https://github.com/NicolasPrats/DvBrowser/tree/features/customapi).  Here is the current status of what is working so far:

- [X]  Unbound custom api
- [X]  Entity bound custom api
- [ ] Collection bound custom api
- [X] Input parameters with a primitive type
- [X] Input parameters with a complex type
- [X] Output parameters with a primitive type
- [ ] Output parameters with a complex type

If your use cases are covered, I would be happy to get a feedback.

**Comment by NicolasPrats** [comment]
It took some time but the latest provides full support for custom APIs and the integration of the REST builder allows you to initiate easily any web api call you want.
Do not hesitate to open a new issue if necessary.
