### ISSUE TITLE
Alternative to desktop application

### ISSUE THREAD

**Issue by ginow** [NicolasPrats/DvBrowser#44]
I was wondering whether it would be possible to develop this tool entirely to run in browser itself instead of desktop application by using the concept of WebAssembly. This would be better user experience wise as they won't need to download and install or even update the app. The entire app can be shipped as a chrome/Edge/Mozilla/any browser extension, this way users won't need to specify which CRM org they want to connect to, they can simply open the CRM and enable this extension to start debugging.

**Comment by NicolasPrats** [comment]
Hi @ginow,

> I was wondering whether it would be possible to develop this tool entirely to run in browser itself instead of desktop application by using the concept of WebAssembly.

Thank you for this suggestion.

I concur completely with your viewpoint: integrating a browser extension would undoubtedly enhance the user experience. However, please note that the tool's capability to execute Dataverse Plugins necessitates the support of a full .NET 4.6 runtime. It isn't readily achievable through WebAssembly or a web browser extension. However, I'm not an expert of WebAssembly, so if you find a way to do that, do not hesitate to share it with me.


An alternative approach involves the utilization of both a desktop application and an extension. The extension would capture requests, transmit them to the application for processing, and subsequently relay the outcomes back to the extension. While this method holds merits in terms of compatibility with major browsers, it does introduce complexities for end users. They would be required to download both an application and an extension, alongside configuring two distinct modules to establish communication.

In the interest of thoroughness, I mention alternative options I had considered previously:

* Creating a web proxy akin to Fiddler: This approach would offer compatibility across all browsers, including mobile apps. However, it necessitates a significantly larger time investment than my current availability allows. Unfortunately, I haven't identified any available libraries to help with that, except the one developed by Telerik, which is not free.

* Developing an extension for Fiddler: This option presents similar challenges to the web browser extension approach.

> this way users won't need to specify which CRM org they want to connect to

This is a minor detail but this requirement isn't inherently tied to the decision to implement a web browser in a desktop app. I need to know which url is associated to which plugin.
