### ISSUE TITLE
How do I change what  url loads in the window?

### ISSUE THREAD

**Issue by devkeydet** [NicolasPrats/DvBrowser#5]
In you LinkedIn post, you mention
![image](https://user-images.githubusercontent.com/4499296/231163513-d7eb5bf2-2a23-44ef-92bf-e5e95d365e4d.png)
How do I change what's in the browser to a canvas app or "web application using the web api"?

**Comment by NicolasPrats** [comment]
Hi @devkeydet ,

For now, there is no integrated way to do that. Until now, I have tested only with embedded canvas-app. However, if your app is standalone, you still can open the devtools and run javascript to change the url: `window.location = 'https://myapp.com'`.
Please keep in mind that in mind that in current version batch requests are not yet translated, so it's not very valuable for canvas app (but I work on it).

**Comment by NicolasPrats** [comment]
> It would be great to put a textbox at the top of the screen to let people enter location without needing to drop to devtools. 

Yeah, I totally agree. Whole UI needs some love. But for now, I have focused on making the project working on some specific scenarios.

> I was going to contribute, but getting a build error. Seen this before? If not, I can investigate. ![image](https://user-images.githubusercontent.com/4499296/231184703-330ab4c8-ebdf-45ee-9ab5-102c6f9bc250.png) I tried all the obvious stuff around restoring/updating nuget packages.

I got a lot of issues with CEFSharp but not this one.  What is displayed when you try to restore nuget packages ? If you try the restore from the VS window, you can check in the output window, by selecting the output from "Package Manager".

**Comment by NicolasPrats** [comment]
> I think that has to do with some config in your project file referring to older packages...

Yes that make sens. @ranistar came to [the same conclusion](https://github.com/NicolasPrats/DvBrowser/pull/8)

**Comment by NicolasPrats** [comment]
I close this issue. 
If it's still not working, feel free to contact me again,
