### ISSUE TITLE
Should this work with Custom Pages?

### ISSUE THREAD

**Issue by devkeydet** [NicolasPrats/DvBrowser#6]
I have a pretty simple model app with a custom page that calls a flow that calls a custom api. When I click the button on the custom page, results are returned, but the http request to the custom api doesn't show in the list.
![image](https://user-images.githubusercontent.com/4499296/231167608-5dc3a975-40c6-4d2f-8cdc-0b29c4292995.png)

**Comment by NicolasPrats** [comment]
Yes it works with custom pages. But it intercepts only web api calls to the dataverse done from the browser. If your canvas app triggers a flow which does some web api calls, the browser will not see them.

**Comment by NicolasPrats** [comment]
I close this issue. 
If it's still not working, feel free to contact me again,
