### ISSUE TITLE
Unable to launch the start.cmd

### ISSUE THREAD

**Issue by noorahmad-code** [NicolasPrats/DvBrowser#7]
Hi

I am getting the below message when I launch the start.cmd file.

![image](https://user-images.githubusercontent.com/56866510/231220249-8b10339f-d465-4480-a99d-569f19749cae.png)

**Comment by NicolasPrats** [comment]
Hi @noorahmad-code ,

Are you sure you have downloaded the file "Dataverse.Browser V0.0.0.2.zip" and not the source code ? 
If you took the source code, you need to compile the solution and to run it from Visual Studio. The .cmd file is useless in this case.

**Comment by noorahmad-code** [comment]
Hi @NicolasPrats 

Yes you are right, I have downloaded the source code, can you please share when can I find this Zip, I tried to search it in the repo.

**Comment by NicolasPrats** [comment]
> Yes you are right, I have downloaded the source code, can you please share when can I find this Zip, I tried to search it in the repo.
Here is a direct link to the current version: https://github.com/NicolasPrats/DvBrowser/releases/download/V0.0.0.2/Dataverse.Browser.V0.0.0.2.zip

For the next versions: when you are on the home page of the repo, on the right, you have link "Releases". Click on it, then on Assets.

**Comment by NicolasPrats** [comment]
I see that you have put the "https://" in the hostname. Please remove it and try again!
I definitively need to make the app more resilient to configuration mistake and/or more intuitive.

**Comment by NicolasPrats** [comment]
I close this issue. 
If it's still not working, feel free to contact me again,
